### ISSUE TITLE
Criação de Readme 

### ISSUE THREAD

**Issue by arthurs159** [paulorobertovrc/api-rest-spring-boot-angular#1]
Oi Paulo, no seu projeto, senti falta do Readme, acredito que seja bem importante porque o readme é o primeiro contato com o projeto que qualquer pessoa vai ter, e muitas vezes o recrutador nem sabe codar, então ele não irá baixar seu projeto para testar. Isso faz o readme mais importante ainda. Eu recomendo colocar um briefing do projeto, quais foram os seus objetivos ao fazer esse projeto, porque decidiu fazer ele, uma fotos de como ficou o resultado. : )

**Comment by paulorobertovrc** [comment]
Bom dia, Arthur! O Readme já está incluído no repositório.
