### ISSUE TITLE
OrElseThrow() no projeto

### ISSUE THREAD

**Issue by arthurs159** [paulorobertovrc/api-rest-spring-boot-angular#2]
Acredito que seja uma boa prática você utilizar o OrElseThrow() no seu projeto nas partes que você coloca o findById() pois pode ser que o findFirst jogue uma exceção caso não encontre o ID e isso não é muito legal, nessas partes aqui:
![image](https://user-images.githubusercontent.com/77133022/207167512-3cfc42f6-f859-4dba-bd22-c6695dcc8d7b.png)

Penso que nem precisaria do if ali, você simplesmente poderia chamar o findById do repositorio com o OrElseThrow e depois continuar seu código normalmente, já que você está utilizando o noSuchElement, jogaria ele dentro do OrElseThrow e resolveria o problema.

Eai, o que acha de ideia?

**Comment by paulorobertovrc** [comment]
Feito!
<img width="1084" alt="Captura de Tela 2022-12-13 às 10 35 34" src="https://user-images.githubusercontent.com/70707151/207337159-45885e45-8c38-42bc-9d92-75ad5d6d3c8a.png">
